### ISSUE TITLE
无法兼容 @vant/weapp 

### ISSUE THREAD

**Issue by bestony** [WeBankFinTech/wxa#89]
## Description

wxa 可以兼容 vant 组件库的 0.5.1 版本，但无法兼容最新的 1.5 版本。

## Environment

  * Platform: 开发者工具
  * Platform version: 开发者工具
  * Wechat version: 无
  * @wxa/cli2 version:  2.2.8
  * @wxa/core version: 2.0.0-alpha.e7e06c46 
  
## Reproduce

1. 执行 `npm install -s @vant/weapp` 
2. 在  index.wxa 的 config 中添加配置

```
"usingComponents": {
  "van-button": "@vant/weapp/button/index"
}
```

3. 在页面中添加代码 `<van-button type="default">默认按钮</van-button>`， 提示无法找到组件。
4. 实际发现没有在npm目录生成 `@vant` 相应目录

### Observed Results

无法兼容 vant-ui 最新版
  
### Expected Results

可以正常兼容 vant-ui 最新版

**Comment by Genuifx** [comment]
没有找到依赖的原因是 `cli` 仅仅检索了 package.json 中的`main` `browser` 不会检查 `miniprogram`，


现版本可以直接像下面这样使用
```
"usingComponents": {
  "van-button": "@vant/weapp/dist/button/index"
}
```

不过这并不符合我们的初衷，我们将尽快支持 component 的 package 检索

**Comment by Genuifx** [comment]
@bestony @wxa/cli2@2.3.0-alpha.2 使用这个版本试试

**Comment by bestony** [comment]
![image](https://user-images.githubusercontent.com/13283837/95684186-68b44c80-0c22-11eb-8dbc-5cddf748cdf9.png)
依然无法兼容

**Comment by Genuifx** [comment]
发布错误版本，代码在 `dev-feat-npm-resolve`

**Comment by bestony** [comment]
wxa 的某些组件无法使用，比如 Field

https://vant-contrib.gitee.io/vant-weapp/#/field

```
> Building Project: default AT: 5/24/2021, 1:44:54 PM
COMPILING: src/request.js
> Resolve Error
file: /Users/bestony/developer/minapp/minapp-x/node_modules/@vant/weapp/dist/field/index.wxml
code: textarea.wxml
Error: 文件不存在
    at DependencyResolver.resolveDep (/Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/helpers/dependencyResolver.js:51:31)
    at XMLManager.findLinkDeps (/Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:117:14)
    at XMLManager.findDeps (/Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:98:24)
    at XMLManager.walkAttr (/Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:86:93)
    at XMLManager.walkXML (/Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:59:31)
    at /Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:64:32
    at Array.reduce (<anonymous>)
    at XMLManager.walkXML (/Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:63:68)
    at /Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:64:32
    at Array.reduce (<anonymous>)


> Resolve Error
file: /Users/bestony/developer/minapp/minapp-x/node_modules/@vant/weapp/dist/field/index.wxml
code: input.wxml
Error: 文件不存在
    at DependencyResolver.resolveDep (/Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/helpers/dependencyResolver.js:51:31)
    at XMLManager.findLinkDeps (/Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:117:14)
    at XMLManager.findDeps (/Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:98:24)
    at XMLManager.walkAttr (/Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:86:93)
    at XMLManager.walkXML (/Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:59:31)
    at /Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:64:32
    at Array.reduce (<anonymous>)
    at XMLManager.walkXML (/Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:63:68)
    at /Users/bestony/.config/yarn/global/node_modules/@wxa/cli2/dist/resolvers/xml/index.js:64:32
    at Array.reduce (<anonymous>)
```

**Comment by Genuifx** [comment]
@bestony 收到，我们会尽快定位问题

**Comment by Genuifx** [comment]
@bestony 请先试用1.5版本的vant 他们的依赖引入写法跟cli的解析规则有点差异

**Comment by Genuifx** [comment]
@bestony 请使用 `@wxa/cli2@2.3.0-rc.13` 已支持

**Comment by Genuifx** [comment]
Release at 2.3.1

**Comment by Genuifx** [comment]
Release at 2.3.1
